
DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER
( id INTEGER NOT NULL,
  firstname VARCHAR(50) NOT NULL,
  lastname VARCHAR(50) NOT NULL,
  gender VARCHAR(10) NOT NULL,

  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS SELLER;
CREATE TABLE SELLER
( id INTEGER NOT NULL,
  name VARCHAR(50) NOT NULL,

  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT
( id INTEGER NOT NULL,
  name VARCHAR(50) NOT NULL,
  price FLOAT NOT NULL,
  categorie VARCHAR(50) NOT NULL,
  description VARCHAR(50) NOT NULL,

  PRIMARY KEY (id)
);