
DROP TABLE IF EXISTS CUSTOMER CASCADE;
CREATE TABLE CUSTOMER
( id INTEGER NOT NULL,
  firstname VARCHAR(50) NOT NULL,
  lastname VARCHAR(50) NOT NULL,
  gender VARCHAR(10) NOT NULL,

  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS SELLER CASCADE;
CREATE TABLE SELLER
( id INTEGER NOT NULL,
  name VARCHAR(50) NOT NULL,

  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS PRODUCT CASCADE;
CREATE TABLE PRODUCT
( id INTEGER NOT NULL,
  name VARCHAR(50) NOT NULL,
  price FLOAT NOT NULL,
  categorie VARCHAR(50) NOT NULL,
  description VARCHAR(150) NOT NULL,

  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS STOCK CASCADE;
CREATE TABLE STOCK
( id INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  product INTEGER NOT NULL,
  seller INTEGER NOT NULL,

  PRIMARY KEY (id),
  FOREIGN KEY (product) REFERENCES PRODUCT(id),
  FOREIGN KEY (seller) REFERENCES SELLER(id)
);

DROP TABLE IF EXISTS ORDEREDITEM CASCADE;
CREATE TABLE ORDEREDITEM
( id INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  price FLOAT NOT NULL,
  stock INTEGER NOT NULL,

  PRIMARY KEY (id),
  FOREIGN KEY (stock) REFERENCES STOCK(id)
);